/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "protolink.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Command, Command, AUTO)


PB_BIND(UpdateFB, UpdateFB, AUTO)


PB_BIND(Result, Result, AUTO)




